apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: $APP_NAME
spec:
  template:
    spec:
      containers:
        - image: gcr.io/$PROJECT_ID/$APP_NAME:$GITHUB_SHA
          envFrom:
            - secretRef:
                name: mongo-secret
